S_A   = $C8
S_B   = $C9
S_C   = $CA
S_D   = $CB
S_E   = $CC
S_F   = $CD
S_G   = $CE
S_H   = $CF
S_I   = $D0
S_J   = $D1
S_K   = $D2
S_L   = $D3
S_M   = $D4
S_N   = $D5
S_O   = $D6
S_P   = $D7
S_Q   = $D8
S_R   = $D9
S_S   = $DA
S_T   = $DB
S_U   = $DC
S_V   = $DD
S_W   = $DE
S_X   = $DF
S_Y   = $E0
S_Z   = $E1
S_0		= $E2
S_1		= $E3
S_2		= $E4
S_3		= $E5
S_4		= $E6
S_5		= $E7
S_6		= $E8
S_7		= $E9
S_8 	= $EA
S_9		= $EB


; default
;S_A  =  $c8  ; screen code for A
;S_B  =  $02  ; screen code for B
;S_C  =  $03  ; screen code for C
;S_D  =  $04  ; screen code for D
;S_E  =  $05  ; screen code for E
;S_F  =  $06  ; screen code for F
;S_G  =  $07  ; screen code for G
;S_H  =  $08  ; screen code for H
;S_I  =  $09  ; screen code for I
;S_J  =  $0A  ; screen code for J
;S_K  =  $0B  ; screen code for K
;S_L  =  $0C  ; screen code for L
;S_M  =  $0D  ; screen code for M
;S_N  =  $0E  ; screen code for N
;S_O  =  $0F  ; screen code for O
;S_P  =  $10  ; screen code for P
;S_Q  =  $11  ; screen code for Q
;S_R  =  $12  ; screen code for R
;S_S  =  $13  ; screen code for S
;S_T  =  $14  ; screen code for T
;S_U  =  $15  ; screen code for U
;S_V  =  $16  ; screen code for V
;S_W  =  $17  ; screen code for W
;S_X  =  $18  ; screen code for X
;S_Y  =  $19  ; screen code for Y
;S_Z  =  $1A  ; screen code for Z


