S_A   = $76
S_B   = S_A+1
S_C   = S_A+2
S_D   = S_A+3
S_E   = S_A+4
S_F   = S_A+5
S_G   = S_A+6
S_H   = S_A+7
S_I   = S_A+8
S_J   = S_A+9
S_K   = S_A+10
S_L   = S_A+11
S_M   = S_A+12
S_N   = S_A+13
S_O   = S_A+14
S_P   = S_A+15
S_Q   = S_A+16
S_R   = S_A+17
S_S   = S_A+18
S_T   = S_A+19
S_U   = S_A+20
S_V   = S_A+21
S_W   = S_A+22
S_X   = S_A+23
S_Y   = S_A+24
S_Z   = S_A+25
S_0		= $90
S_1		= S_0+1
S_2		= S_0+2
S_3		= S_0+3
S_4		= S_0+4
S_5		= S_0+5
S_6		= S_0+6
S_7		= S_0+7
S_8 	= S_0+8
S_9		= S_0+9

; default
;S_A  =  $c8  ; screen code for A
;S_B  =  $02  ; screen code for B
;S_C  =  $03  ; screen code for C
;S_D  =  $04  ; screen code for D
;S_E  =  $05  ; screen code for E
;S_F  =  $06  ; screen code for F
;S_G  =  $07  ; screen code for G
;S_H  =  $08  ; screen code for H
;S_I  =  $09  ; screen code for I
;S_J  =  $0A  ; screen code for J
;S_K  =  $0B  ; screen code for K
;S_L  =  $0C  ; screen code for L
;S_M  =  $0D  ; screen code for M
;S_N  =  $0E  ; screen code for N
;S_O  =  $0F  ; screen code for O
;S_P  =  $10  ; screen code for P
;S_Q  =  $11  ; screen code for Q
;S_R  =  $12  ; screen code for R
;S_S  =  $13  ; screen code for S
;S_T  =  $14  ; screen code for T
;S_U  =  $15  ; screen code for U
;S_V  =  $16  ; screen code for V
;S_W  =  $17  ; screen code for W
;S_X  =  $18  ; screen code for X
;S_Y  =  $19  ; screen code for Y
;S_Z  =  $1A  ; screen code for Z


